# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class CfaDTO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, token=None, cfa_image_id=None, user_id=None):  # noqa: E501
        """InlineResponse2004 - a model defined in OpenAPI

        :param token: The token of this InlineResponse2004.  # noqa: E501
        :type token: str
        :param cfa_image_id: The cfa_image_id of this InlineResponse2004.  # noqa: E501
        :type cfa_image_id: int
        :param user_id: The user_id of this InlineResponse2004.  # noqa: E501
        :type user_id: int
        """
        self.openapi_types = {
            'token': str,
            'cfa_image_id': int,
            'user_id': int
        }

        self.attribute_map = {
            'token': 'token',
            'cfa_image_id': 'cfa_image_id',
            'user_id': 'user_id'
        }

        self._token = token
        self._cfa_image_id = cfa_image_id
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'CfaDTO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_4 of this InlineResponse2004.  # noqa: E501
        :rtype: CfaDTO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self):
        """Gets the token of this InlineResponse2004.


        :return: The token of this InlineResponse2004.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this InlineResponse2004.


        :param token: The token of this InlineResponse2004.
        :type token: str
        """

        self._token = token

    @property
    def cfa_image_id(self):
        """Gets the cfa_image_id of this InlineResponse2004.


        :return: The cfa_image_id of this InlineResponse2004.
        :rtype: int
        """
        return self._cfa_image_id

    @cfa_image_id.setter
    def cfa_image_id(self, cfa_image_id):
        """Sets the cfa_image_id of this InlineResponse2004.


        :param cfa_image_id: The cfa_image_id of this InlineResponse2004.
        :type cfa_image_id: int
        """

        self._cfa_image_id = cfa_image_id

    @property
    def user_id(self):
        """Gets the user_id of this InlineResponse2004.


        :return: The user_id of this InlineResponse2004.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this InlineResponse2004.


        :param user_id: The user_id of this InlineResponse2004.
        :type user_id: int
        """

        self._user_id = user_id
