# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from openapi_server import util
from openapi_server.models.base_model_ import Model
from openapi_server.models.public_user import PublicUser


class CfaImage(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, title=None, count=None, description=None, user=None):  # noqa: E501
        """CfaImage - a model defined in OpenAPI

        :param id: The id of this CfaImage.  # noqa: E501
        :type id: int
        :param title: The title of this CfaImage.  # noqa: E501
        :type title: str
        :param count: The count of this CfaImage.  # noqa: E501
        :type count: int
        :param description: The description of this CfaImage.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'id': int,
            'title': str,
            'count': int,
            'description': str,
            'user': PublicUser
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'count': 'count',
            'description': 'description',
            'user': 'user'
        }

        self._id = id
        self._title = title
        self._count = count
        self._description = description
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'CfaImage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CfaImage of this CfaImage.  # noqa: E501
        :rtype: CfaImage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this CfaImage.


        :return: The id of this CfaImage.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CfaImage.


        :param id: The id of this CfaImage.
        :type id: int
        """

        self._id = id

    @property
    def title(self):
        """Gets the title of this CfaImage.


        :return: The title of this CfaImage.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this CfaImage.


        :param title: The title of this CfaImage.
        :type title: str
        """

        self._title = title

    @property
    def count(self):
        """Gets the count of this CfaImage.


        :return: The count of this CfaImage.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this CfaImage.


        :param count: The count of this CfaImage.
        :type count: int
        """

        self._count = count

    @property
    def description(self):
        """Gets the description of this CfaImage.


        :return: The description of this CfaImage.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CfaImage.


        :param description: The description of this CfaImage.
        :type description: str
        """

        self._description = description

    @property
    def user(self):
        """Gets the user of this CfaImage.


        :return: The user of this CfaImage.
        :rtype: PublicUser
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this CfaImage.


        :param user: The title of this CfaImage.
        :type user: PublicUser
        """

        self._user = user
