# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class CfaPriceDTO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, price=None):  # noqa: E501
        """CfaPriceDTO - a model defined in OpenAPI

        :param price: The price of this CfaPriceDTO.  # noqa: E501
        :type price: int
        """
        self.openapi_types = {
            'price': int
        }

        self.attribute_map = {
            'price': 'price'
        }

        self._price = price

    @classmethod
    def from_dict(cls, dikt) -> 'CfaPriceDTO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cfa_price_dto of this CfaPriceDTO.  # noqa: E501
        :rtype: CfaPriceDTO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def price(self):
        """Gets the price of this CfaPriceDTO.


        :return: The price of this CfaPriceDTO.
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this CfaPriceDTO.


        :param price: The price of this CfaPriceDTO.
        :type price: int
        """

        self._price = price
