# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from openapi_server import util
from openapi_server.models.base_model_ import Model


class DepositValueDTO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, value=None):  # noqa: E501
        """DepositValueDTO - a model defined in OpenAPI

        :param value: The value of this DepositValueDTO.  # noqa: E501
        :type value: int
        """
        self.openapi_types = {
            'value': int
        }

        self.attribute_map = {
            'value': 'value'
        }

        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'DepositValueDTO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The deposit_value_dto of this DepositValueDTO.  # noqa: E501
        :rtype: DepositValueDTO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self):
        """Gets the value of this DepositValueDTO.


        :return: The value of this DepositValueDTO.
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this DepositValueDTO.


        :param value: The value of this DepositValueDTO.
        :type value: int
        """

        self._value = value
