# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class CreateCfaImageDTO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, count=None, description=None):  # noqa: E501
        """InlineObject2 - a model defined in OpenAPI

        :param title: The title of this InlineObject2.  # noqa: E501
        :type title: str
        :param count: The count of this InlineObject2.  # noqa: E501
        :type count: int
        :param description: The description of this InlineObject2.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'title': str,
            'count': int,
            'description': str
        }

        self.attribute_map = {
            'title': 'title',
            'count': 'count',
            'description': 'description'
        }

        self._title = title
        self._count = count
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'CreateCfaImageDTO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object_2 of this InlineObject2.  # noqa: E501
        :rtype: CreateCfaImageDTO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self):
        """Gets the title of this InlineObject2.


        :return: The title of this InlineObject2.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this InlineObject2.


        :param title: The title of this InlineObject2.
        :type title: str
        """

        self._title = title

    @property
    def count(self):
        """Gets the count of this InlineObject2.


        :return: The count of this InlineObject2.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this InlineObject2.


        :param count: The count of this InlineObject2.
        :type count: int
        """

        self._count = count

    @property
    def description(self):
        """Gets the description of this InlineObject2.


        :return: The description of this InlineObject2.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this InlineObject2.


        :param description: The description of this InlineObject2.
        :type description: str
        """

        self._description = description
