# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, title=None, count=None, description=None):  # noqa: E501
        """InlineResponse2002 - a model defined in OpenAPI

        :param id: The id of this InlineResponse2002.  # noqa: E501
        :type id: int
        :param title: The title of this InlineResponse2002.  # noqa: E501
        :type title: str
        :param count: The count of this InlineResponse2002.  # noqa: E501
        :type count: int
        :param description: The description of this InlineResponse2002.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'id': int,
            'title': str,
            'count': int,
            'description': str
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'count': 'count',
            'description': 'description'
        }

        self._id = id
        self._title = title
        self._count = count
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this InlineResponse2002.


        :return: The id of this InlineResponse2002.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2002.


        :param id: The id of this InlineResponse2002.
        :type id: int
        """

        self._id = id

    @property
    def title(self):
        """Gets the title of this InlineResponse2002.


        :return: The title of this InlineResponse2002.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this InlineResponse2002.


        :param title: The title of this InlineResponse2002.
        :type title: str
        """

        self._title = title

    @property
    def count(self):
        """Gets the count of this InlineResponse2002.


        :return: The count of this InlineResponse2002.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this InlineResponse2002.


        :param count: The count of this InlineResponse2002.
        :type count: int
        """

        self._count = count

    @property
    def description(self):
        """Gets the description of this InlineResponse2002.


        :return: The description of this InlineResponse2002.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this InlineResponse2002.


        :param description: The description of this InlineResponse2002.
        :type description: str
        """

        self._description = description
