# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from openapi_server import util
from openapi_server.models.base_model_ import Model
from openapi_server.models.user import User


class LoginResponse200(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user=None, bearer_token=None):  # noqa: E501
        """LoginResponse200 - a model defined in OpenAPI

        :param user: The user of this LoginResponse200.  # noqa: E501
        :type user: User
        :param bearer_token: The bearer_token of this LoginResponse200.  # noqa: E501
        :type bearer_token: str
        """
        self.openapi_types = {
            'user': User,
            'bearer_token': str
        }

        self.attribute_map = {
            'user': 'user',
            'bearer_token': 'bearer_token'
        }

        self._user = user
        self._bearer_token = bearer_token

    @classmethod
    def from_dict(cls, dikt) -> 'LoginResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The login_response_200 of this LoginResponse200.  # noqa: E501
        :rtype: LoginResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self):
        """Gets the user of this LoginResponse200.


        :return: The user of this LoginResponse200.
        :rtype: int
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this LoginResponse200.


        :param user: The user of this LoginResponse200.
        :type user: int
        """

        self._user = user

    @property
    def bearer_token(self):
        """Gets the bearer_token of this LoginResponse200.


        :return: The bearer_token of this LoginResponse200.
        :rtype: str
        """
        return self._bearer_token

    @bearer_token.setter
    def bearer_token(self, bearer_token):
        """Sets the bearer_token of this LoginResponse200.


        :param bearer_token: The bearer_token of this LoginResponse200.
        :type bearer_token: str
        """

        self._bearer_token = bearer_token
