# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from openapi_server import util
from openapi_server.models.base_model_ import Model


class LoginResponse200(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None, bearer_token=None):  # noqa: E501
        """InlineResponse2001 - a model defined in OpenAPI

        :param user_id: The user_id of this InlineResponse2001.  # noqa: E501
        :type user_id: int
        :param bearer_token: The bearer_token of this InlineResponse2001.  # noqa: E501
        :type bearer_token: str
        """
        self.openapi_types = {
            'user_id': int,
            'bearer_token': str
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'bearer_token': 'bearer_token'
        }

        self._user_id = user_id
        self._bearer_token = bearer_token

    @classmethod
    def from_dict(cls, dikt) -> 'LoginResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: LoginResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self):
        """Gets the user_id of this InlineResponse2001.


        :return: The user_id of this InlineResponse2001.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this InlineResponse2001.


        :param user_id: The user_id of this InlineResponse2001.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def bearer_token(self):
        """Gets the bearer_token of this InlineResponse2001.


        :return: The bearer_token of this InlineResponse2001.
        :rtype: str
        """
        return self._bearer_token

    @bearer_token.setter
    def bearer_token(self, bearer_token):
        """Sets the bearer_token of this InlineResponse2001.


        :param bearer_token: The bearer_token of this InlineResponse2001.
        :type bearer_token: str
        """

        self._bearer_token = bearer_token
