# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from openapi_server import util
from openapi_server.models.base_model_ import Model


class LoginUserDTO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, email=None, password=None):  # noqa: E501
        """emailUserDTO - a model defined in OpenAPI

        :param email: The email of this emailUserDTO.  # noqa: E501
        :type email: str
        :param password: The password of this emailUserDTO.  # noqa: E501
        :type password: str
        """
        self.openapi_types = {
            'email': str,
            'password': str
        }

        self.attribute_map = {
            'email': 'email',
            'password': 'password'
        }

        self._email = email
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'emailUserDTO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The email_user_dto of this emailUserDTO.  # noqa: E501
        :rtype: emailUserDTO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self):
        """Gets the email of this emailUserDTO.


        :return: The email of this emailUserDTO.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this emailUserDTO.


        :param email: The email of this emailUserDTO.
        :type email: str
        """

        self._email = email

    @property
    def password(self):
        """Gets the password of this emailUserDTO.


        :return: The password of this emailUserDTO.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this emailUserDTO.


        :param password: The password of this emailUserDTO.
        :type password: str
        """

        self._password = password
