# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class RegisterUserDTO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, login=None, username=None, name=None, password=None):  # noqa: E501
        """InlineObject - a model defined in OpenAPI

        :param login: The login of this InlineObject.  # noqa: E501
        :type login: str
        :param username: The username of this InlineObject.  # noqa: E501
        :type username: str
        :param name: The name of this InlineObject.  # noqa: E501
        :type name: str
        :param password: The password of this InlineObject.  # noqa: E501
        :type password: str
        """
        self.openapi_types = {
            'login': str,
            'username': str,
            'name': str,
            'password': str
        }

        self.attribute_map = {
            'login': 'login',
            'username': 'username',
            'name': 'name',
            'password': 'password'
        }

        self._login = login
        self._username = username
        self._name = name
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'RegisterUserDTO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object of this InlineObject.  # noqa: E501
        :rtype: RegisterUserDTO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def login(self):
        """Gets the login of this InlineObject.


        :return: The login of this InlineObject.
        :rtype: str
        """
        return self._login

    @login.setter
    def login(self, login):
        """Sets the login of this InlineObject.


        :param login: The login of this InlineObject.
        :type login: str
        """

        self._login = login

    @property
    def username(self):
        """Gets the username of this InlineObject.


        :return: The username of this InlineObject.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this InlineObject.


        :param username: The username of this InlineObject.
        :type username: str
        """

        self._username = username

    @property
    def name(self):
        """Gets the name of this InlineObject.


        :return: The name of this InlineObject.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineObject.


        :param name: The name of this InlineObject.
        :type name: str
        """

        self._name = name

    @property
    def password(self):
        """Gets the password of this InlineObject.


        :return: The password of this InlineObject.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this InlineObject.


        :param password: The password of this InlineObject.
        :type password: str
        """

        self._password = password
