# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class TradeDTO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, date=None, cfa_token=None, price=None, buyer_id=None, seller_id=None):  # noqa: E501
        """InlineResponse2005 - a model defined in OpenAPI

        :param id: The id of this InlineResponse2005.  # noqa: E501
        :type id: int
        :param date: The date of this InlineResponse2005.  # noqa: E501
        :type date: str
        :param cfa_token: The cfa_token of this InlineResponse2005.  # noqa: E501
        :type cfa_token: str
        :param price: The price of this InlineResponse2005.  # noqa: E501
        :type price: int
        :param buyer_id: The buyer_id of this InlineResponse2005.  # noqa: E501
        :type buyer_id: int
        :param seller_id: The seller_id of this InlineResponse2005.  # noqa: E501
        :type seller_id: int
        """
        self.openapi_types = {
            'id': int,
            'date': str,
            'cfa_token': str,
            'price': int,
            'buyer_id': int,
            'seller_id': int
        }

        self.attribute_map = {
            'id': 'id',
            'date': 'date',
            'cfa_token': 'cfa_token',
            'price': 'price',
            'buyer_id': 'buyer_id',
            'seller_id': 'seller_id'
        }

        self._id = id
        self._date = date
        self._cfa_token = cfa_token
        self._price = price
        self._buyer_id = buyer_id
        self._seller_id = seller_id

    @classmethod
    def from_dict(cls, dikt) -> 'TradeDTO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5 of this InlineResponse2005.  # noqa: E501
        :rtype: TradeDTO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this InlineResponse2005.


        :return: The id of this InlineResponse2005.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2005.


        :param id: The id of this InlineResponse2005.
        :type id: int
        """

        self._id = id

    @property
    def date(self):
        """Gets the date of this InlineResponse2005.


        :return: The date of this InlineResponse2005.
        :rtype: str
        """
        return self._date

    @date.setter
    def date(self, date):
        """Sets the date of this InlineResponse2005.


        :param date: The date of this InlineResponse2005.
        :type date: str
        """

        self._date = date

    @property
    def cfa_token(self):
        """Gets the cfa_token of this InlineResponse2005.


        :return: The cfa_token of this InlineResponse2005.
        :rtype: str
        """
        return self._cfa_token

    @cfa_token.setter
    def cfa_token(self, cfa_token):
        """Sets the cfa_token of this InlineResponse2005.


        :param cfa_token: The cfa_token of this InlineResponse2005.
        :type cfa_token: str
        """

        self._cfa_token = cfa_token

    @property
    def price(self):
        """Gets the price of this InlineResponse2005.


        :return: The price of this InlineResponse2005.
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this InlineResponse2005.


        :param price: The price of this InlineResponse2005.
        :type price: int
        """

        self._price = price

    @property
    def buyer_id(self):
        """Gets the buyer_id of this InlineResponse2005.


        :return: The buyer_id of this InlineResponse2005.
        :rtype: int
        """
        return self._buyer_id

    @buyer_id.setter
    def buyer_id(self, buyer_id):
        """Sets the buyer_id of this InlineResponse2005.


        :param buyer_id: The buyer_id of this InlineResponse2005.
        :type buyer_id: int
        """

        self._buyer_id = buyer_id

    @property
    def seller_id(self):
        """Gets the seller_id of this InlineResponse2005.


        :return: The seller_id of this InlineResponse2005.
        :rtype: int
        """
        return self._seller_id

    @seller_id.setter
    def seller_id(self, seller_id):
        """Sets the seller_id of this InlineResponse2005.


        :param seller_id: The seller_id of this InlineResponse2005.
        :type seller_id: int
        """

        self._seller_id = seller_id
